### PR TITLE
Version update from 100.12 to 100.13

### PR DESCRIPTION
**Pull request by mfeigl**
Updating the version from 100.12 to 100.13
@tanneryould could you please review this PR?

### CODE REVIEW

**Comment by tanneryould** [comment]
In an attempt to be helpful, I resolved the merge conflicts and pushed commit `Merge branch 'v.next' into marton/100.13` which sounds more significant than it actually is

**Review by tanneryould — APPROVED** [review]
LGTM

**Comment by mfeigl** [comment]
Thanks for the merge @tanneryould , I had thought I branched off from an up to date version of `v.next`. 
Resolving the merge conflict did mean that there were new files to update - could I please ask you for a second review?

**Review by tanneryould — APPROVED** [review]
Good catch on the new files. LGTM

**Pull request merged**
