### PR TITLE
Release/100.11.0

### PR DESCRIPTION
**Pull request by JamesMBallard**

### CODE REVIEW

**Comment by JamesMBallard** [comment]
@jared-2016 please review. This is merging release/100.11.0 to master.

FYI @tanneryould

**Comment by JamesMBallard** [comment]
@tanneryould please review as well. I did some git-fu merging master into this branch. Please spot check everything looks ok.

**Review by jared-2016 — APPROVED** [review]
Looks good to me. I am guessing that @tanneryould could either fix the formatting mistakes that were caught by the git hook or write up a samples issue to fix them at a later point.

**Review by tanneryould — APPROVED** [review]
I need to merge some metadata style checks into v.next (I thought it ran off master, but perhaps not). The check raises false errors and is otherwise good to go. Approved.

**Pull request merged**
