### PR TITLE
Jcaccamo/update closest faclilty name

### PR DESCRIPTION
**Pull request by jared-esri**
@ldanzinger Ready for review. Just updating the name of the samples.

Also came across some inconsistencies in the comments at the top of the file. Does the value for "WriteFile Name=" matter? I updated them for consistency. Let me know if I need to revert it back.

### CODE REVIEW

**Comment by ldanzinger** [comment]
looks good. Let's hold still until after the release to merge

**Comment by ldanzinger** [comment]
@jared-esri I believe those tags no longer matter. They used to be used for the doc build for pulling snippets. I'm not sure that they are any longer.

**Comment by jared-esri** [comment]
@ldanzinger I'll leave the change in then. 👍

**Comment by ldanzinger** [comment]
@jared-esri this one can be merged now that the code base is open

**Pull request merged**
