### PR TITLE
Add the necessary header so Local Server can be detected.

### PR DESCRIPTION
**Pull request by JamesMBallard**
# Description

Fix the local server detection logic.

## Type of change

- [x] Bug fix

### CODE REVIEW

**Review by tanneryould — APPROVED** [review]
LGTM

**Comment by ldanzinger** [comment]
I guess we need to add this include into https://github.com/Esri/arcgis-runtime-samples-qt/blob/v.next/ArcGISRuntimeSDKQt_SampleViewers/ArcGISRuntimeSDKQt_Samples/SampleManager.cpp and https://github.com/Esri/arcgis-runtime-samples-qt/blob/v.next/ArcGISRuntimeSDKQt_SampleViewers/ArcGISRuntimeSDKQt_Samples/mainSample.cpp since they use LOCALSERVER_SUPPORTED?

**Comment by JamesMBallard** [comment]
Right you are!
https://github.com/Esri/arcgis-runtime-samples-qt/pull/1547/files

**Comment by JamesMBallard** [comment]
I logged a separate issue to consider refactoring how these headers work so they can be included anywhere without errors. That would prevent problems like this in the future.

**Pull request merged**
