### PR TITLE
Marton/100.15

### PR DESCRIPTION
**Pull request by mfeigl**
Updating the version from 100.14 to 100.15

@tanneryould and @Gela may I please ask you to review this PR?

### CODE REVIEW

**Review by tanneryould — CHANGES_REQUESTED** [review]
A couple of missed 100.13 and 100.14 cases -- see my following comment

**Comment by tanneryould** [comment]
Screen Shot 2022-04-27 at 11 26 27 AM
Screen Shot 2022-04-27 at 11 26 36 AM

**Comment by tanneryould** [comment]
Screen Shot 2022-04-27 at 11 26 27 AM
Screen Shot 2022-04-27 at 11 26 36 AM

**Comment by mfeigl** [comment]
Thank you @tanneryould ! I corrected the occurrences you found, with the exception of `As of update 100.13, C++ samples' README.metadata.json snippets should list the primary C++ first` as I think it's referring to a historical point in time and ought to remain as is - I re-requested your review.

**Review by tanneryould — APPROVED** [review]
LGTM

**Pull request merged**
