### PR TITLE
Cherry picking basemapStyle/API branch into master

### PR DESCRIPTION
**Pull request by tanneryould**

### CODE REVIEW

**Review by jared-2016 — APPROVED** [review]
Looks good to me. 👍

**Comment by tanneryould** [comment]
The failing checks are a false negative and the result of a sort that is case sensitive and in the title check. I need to update those so the sort is case insensitive and the title check is a bit more lenient.

**Comment by tanneryould** [comment]
@ldanzinger were you able to take a look at this?

**Review by ldanzinger — APPROVED** [review]
Spot checked QML & C++. Looks good

**Comment by tanneryould** [comment]
Changes approved. Merging into master.

**Pull request merged**
