### PR TITLE
updating the version number from 100.11 to 100.12

### PR DESCRIPTION
**Pull request by mfeigl**
Updating the version from 100.11 to 100.12

### CODE REVIEW

**Review by JamesMBallard — APPROVED** [review]
👍

**Comment by JamesMBallard** [comment]
@tanneryould the git checks are failing for this. Do we need to address that before merging?

**Comment by tanneryould** [comment]
@JamesMBallard fortunately there are only two errors. I'd like to resolve this before merging and it shouldn't take too long.

**Comment by tanneryould** [comment]
@JamesMBallard ok, the check is raising a false error. The OAuth Redirect Example doesn't follow the standard md pattern so I'm going to open a PR to add this file as an extension. In the meantime, this is good to go.

**Review by tanneryould — APPROVED** [review]
Check raises false failure. All tests pass.

**Pull request merged**
