### PR TITLE
Fix DisplayFilter QML property

### PR DESCRIPTION
**Pull request by tanneryould**
The DisplayFilter object should have a `name` not an `id`. `id` is reserved and `filterId` is read-only.

### CODE REVIEW

**Comment by tanneryould** [comment]
@Gela I'm not super familiar with this sample, but it looks like the `DisplayFilter`'s name in the [C++ implementation](https://github.com/Esri/arcgis-runtime-samples-qt/blob/v.next/ArcGISRuntimeSDKQt_CppSamples/Features/FilterByDefinitionExpressionOrDisplayFilter/FilterByDefinitionExpressionOrDisplayFilter.cpp#L139) is "Damaged Trees" and not "No Filter" like it is in QML. Similarly its `whereClause` is just `""` and not `"1=1"` like it is in QML. The `whereClause` doesn't seem to have an effect, but should we update either (or both) of these for parity between the two?

**Comment by Gela** [comment]
Yes I agree

**Comment by tanneryould** [comment]
@Gela I believe this is ready for review.
@GuillaumeBelz and @JamesMBallard, your review is welcomed but not necessary.

Thank you!

**Review by Gela — APPROVED** [review]
Oops, thought I approved it when I commented last night. LGTM

**Review by GuillaumeBelz — CHANGES_REQUESTED** [review]
Some names don't follow the usages, can you rename `available_filters` and `display_filter_defintion`?

**Comment by GuillaumeBelz** [comment]
@Gela Thank you, I didn't know.

**Review by GuillaumeBelz — APPROVED** [review]

**Pull request merged**
